// Driving the wizard without a person.
//
// The interactive path is covered by wizard.test.js. This is the other caller: something
// that supplies answers by key, takes defaults for the rest, and reads the result as
// data. The two share one interview — a question added for a human is immediately
// settable by an agent, and the coverage test below is what keeps that true.

import { test, expect } from 'bun:test';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { createProject, describeQuestions } from '../src/index.js';
import { presetPrompter, recordingPrompter, scripted } from '../src/prompt.js';

const fileNamed = (files, p) => files.find((f) => f.path === p);

// --- the guard that keeps --describe honest -----------------------------------

test('every question the wizard asks is one --describe reports', async () => {
  // The schema is generated by walking the interview rather than kept by hand, so it
  // cannot go stale — unless a question is added on a branch the walk never reaches,
  // which is exactly what this catches. Without it, `--set some.new.key=x` would fail
  // with "never asked for" and the only way to find the right key would be reading
  // plan.js.
  const described = new Set((await describeQuestions({})).map((q) => q.key));
  const src = readFileSync(path.resolve(import.meta.dir, '../src/plan.js'), 'utf8');
  const inCode = new Set([...src.matchAll(/key: '([^']+)'/g)].map((m) => m[1]));

  expect(inCode.size).toBeGreaterThan(50);
  expect([...inCode].filter((k) => !described.has(k))).toEqual([]);
});

test('a choice is described with every value it accepts, across runtimes', async () => {
  const qs = await describeQuestions({});
  const driver = qs.find((q) => q.key === 'storage.driver');
  // Workers has no disk and does not offer `filesystem`; bun and node do. The union is
  // what a caller needs, or --describe would omit a value the wizard accepts.
  expect(driver.options.map((o) => o.value).sort()).toEqual(['filesystem', 'memory', 's3']);
  expect(qs.find((q) => q.key === 'workers.d1.id').runtimes).toEqual(['workers']);
  expect(qs.find((q) => q.key === 'metadata.path').runtimes.sort()).toEqual(['bun', 'node']);
});

// --- supplying answers ----------------------------------------------------------

test('answers by key configure the project, and the rest take defaults', async () => {
  const { files, plan, unused } = await createProject({
    name: 'drive', version: '9.9.9', runtime: 'workers',
    answers: {
      'storage.bucket': 'acme-objects',
      'storage.accessKeyId': 'AKIA1',
      'storage.secretAccessKey': 'shh',
      'identity.driver': 'cloudflare-access',
      'identity.team': 'acme',
      'identity.aud': 'aud-123',
      'workers.d1.id': 'db-abc',
    },
  });
  expect(unused).toEqual([]);

  const toml = fileNamed(files, 'wrangler.toml').contents;
  expect(toml).toContain('TROVE_S3_BUCKET = "acme-objects"');
  expect(toml).toContain('TROVE_CF_ACCESS_TEAM = "acme"');
  expect(toml).toContain('database_id = "db-abc"');
  // The rule that has to survive every other path into this code.
  expect(toml).not.toContain('shh');
  expect(fileNamed(files, '.dev.vars.example').contents).toContain('TROVE_S3_SECRET_ACCESS_KEY=shh');

  // A fully configured identity is not warned about; the default one is.
  expect(plan.warnings).toEqual([]);
});

test('booleans are accepted in the spellings a shell produces', async () => {
  for (const [given, expected] of [['true', true], ['false', false], ['yes', true], ['no', false], ['1', true], ['0', false]]) {
    const { plan } = await createProject({
      name: 'd', version: '1.0.0', runtime: 'node', answers: { 'metadata.enabled': given },
    });
    expect(plan.skipped.includes('Metadata')).toBe(!expected);
  }
});

test('a value outside a choice names the key rather than failing obscurely', async () => {
  const attempt = createProject({
    name: 'd', version: '1.0.0', runtime: 'node', answers: { 'identity.driver': 'magic' },
  });
  await expect(attempt).rejects.toThrow(/identity\.driver.*not one of/);
});

test('a boolean that is not one refuses rather than guessing', async () => {
  const attempt = createProject({
    name: 'd', version: '1.0.0', runtime: 'node', answers: { 'metadata.enabled': 'maybe' },
  });
  await expect(attempt).rejects.toThrow(/metadata\.enabled.*boolean/);
});

// --- answers that go nowhere ------------------------------------------------------

test('an answer that was never asked for is reported, not swallowed', async () => {
  // Both cases matter to a caller that cannot see the interview: a typo, and a setting
  // another answer ruled out. Silently dropping either means an agent thinks it
  // configured a bucket and gets a drive without one.
  const typo = await createProject({
    name: 'd', version: '1.0.0', runtime: 'node', answers: { 'storage.buckett': 'x' },
  });
  expect(typo.unused).toEqual(['storage.buckett']);

  const unreachable = await createProject({
    name: 'd', version: '1.0.0', runtime: 'node',
    answers: { 'storage.driver': 'filesystem', 'storage.bucket': 'x' },
  });
  expect(unreachable.unused).toEqual(['storage.bucket']);
});

// --- the prompters themselves ------------------------------------------------------

test('a preset answer wins, and anything unanswered falls through', async () => {
  const inner = scripted([['  Bucket', 'from-the-prompt']]);
  const p = presetPrompter({ 'storage.region': 'auto' }, inner);
  expect(await p.text('  Region', { key: 'storage.region', default: 'us-east-1' })).toBe('auto');
  expect(await p.text('  Bucket', { key: 'storage.bucket', default: 'trove' })).toBe('from-the-prompt');
  expect(p.unused()).toEqual([]);
});

test('the recorder answers with defaults and writes down what it was asked', async () => {
  const rec = recordingPrompter();
  expect(await rec.choice('  Backend', [{ value: 'a', label: 'A' }, { value: 'b', label: 'B' }],
    { key: 'storage.driver', default: 'b' })).toBe('b');
  expect(rec.questions()).toEqual([{
    key: 'storage.driver', kind: 'choice', label: 'Backend', default: 'b',
    options: [{ value: 'a', label: 'A' }, { value: 'b', label: 'B' }],
  }]);
});
