// The programmatic surface.
//
// The CLI is one caller of this, not the only way in. `exports` previously named
// `./plan` alone, which was not usable: `askPlan` needs a prompter, and neither the
// prompter nor the renderer was exported. So the package advertised a library entry
// that could not build anything.
//
// Everything here is non-interactive by construction — no terminal is touched unless a
// caller passes a prompter that wants one. That is the shape an agent needs: supply the
// answers it knows, take defaults for the rest, and get files back as data rather than
// as a directory it then has to go and read.

import { presetPrompter, recordingPrompter, createPrompter } from './prompt.js';
import { askPlan, RUNTIMES } from './plan.js';
import { renderProject } from './render.js';

export { askPlan, renderProject, RUNTIMES };
export { createPrompter, presetPrompter, recordingPrompter, scripted } from './prompt.js';

/**
 * Plan and render a project without asking anybody anything.
 *
 * @param {object} opts
 * @param {string} opts.name project (and package) name
 * @param {string} opts.version the @3sln/trove version to pin
 * @param {string} [opts.runtime] bun | node | workers; also settable as answers.runtime
 * @param {Record<string, string|boolean|number>} [opts.answers] keyed answers — see
 *   `describeQuestions()` for what the keys are
 * @param {object} [opts.prompter] asked about anything `answers` does not cover;
 *   defaults to one that takes every default and never blocks
 * @returns {Promise<{plan: object, files: Array, steps: Array, unused: string[]}>}
 *   `unused` is the answers that were never asked for — a typo, or a setting the other
 *   answers made unreachable. Both are worth surfacing rather than swallowing.
 */
/** Somewhere for headings to go that is not a caller's stdout. */
const SILENT = { write() {}, isTTY: false };

export async function createProject({ name, version, runtime, answers = {}, prompter } = {}) {
  // Silent unless the caller hands over a prompter that wants to talk. A library that
  // prints section headings to stdout cannot be used inside anything that emits
  // structured output — which is most of what would want to call this.
  const base = prompter ?? createPrompter({ assumeDefaults: true, output: SILENT });
  const preset = presetPrompter(answers, base);
  const plan = await askPlan(preset, { name, version, runtime: runtime ?? undefined });
  const { files, steps } = renderProject(plan);
  return { plan, files, steps, unused: preset.unused() };
}

/**
 * Every question the wizard can ask, by key.
 *
 * Generated by running the interview rather than kept by hand, because the interview
 * branches on its own answers and a hand-written schema would drift from it the first
 * time a question moved. Running it once per runtime with a recorder covers the three
 * shapes that actually differ; a question only reachable under a non-default answer
 * (Qdrant's URL, say) is reported against the answer that reveals it via `revealedBy`.
 *
 * @param {object} [opts]
 * @param {string} [opts.version] only affects the plan, not the questions
 */
export async function describeQuestions({ version = '0.0.0' } = {}) {
  const byKey = new Map();

  const run = async (runtime, answers) => {
    const rec = recordingPrompter();
    try {
      // `runtime: undefined` lets the runtime question itself be asked and recorded;
      // passing it skips the question, which is how it went undocumented at first.
      await askPlan(presetPrompter(answers, rec), { name: 'example', version, runtime });
    } catch {
      // The combination does not exist — `storage.driver=filesystem` under Workers,
      // which has no disk and so does not offer it. Not every pairing of answers is a
      // reachable state, and probing for that is the point.
      return false;
    }
    let discovered = false;
    for (const q of rec.questions()) {
      const seen = byKey.get(q.key);
      if (!seen) {
        byKey.set(q.key, { ...q, runtimes: [runtime ?? 'bun'] });
        discovered = true;
      } else {
        if (runtime && !seen.runtimes.includes(runtime)) seen.runtimes.push(runtime);
        // A choice can offer different options per runtime, so the description is the
        // union — otherwise `--describe` would reject a value the wizard accepts.
        for (const o of q.options ?? []) {
          if (!seen.options.some((x) => x.value === o.value)) seen.options.push(o);
        }
      }
    }
    return discovered;
  };

  // The interview branches on its own answers, so one pass describes only the path the
  // defaults take. Walking it to a fixed point — turn every section on, then try each
  // alternative of every choice, then give every empty text field a value — reaches the
  // questions that only exist under some other answer: Qdrant's URL, the JWT fields,
  // the icon size that appears once an icon is named. It is bounded by the question set
  // rather than by a guess, and it cannot drift from the code the way a hand-kept
  // schema would.
  await run(undefined, {});
  for (const runtime of RUNTIMES) await run(runtime, {});

  for (let round = 0; round < 4; round++) {
    const on = Object.fromEntries([...byKey.keys()].filter((k) => k.endsWith('.enabled')).map((k) => [k, true]));
    let discovered = false;

    for (const runtime of RUNTIMES) {
      if (await run(runtime, on)) discovered = true;

      for (const q of [...byKey.values()]) {
        // Each alternative of a choice, one at a time, so a reveal is attributable.
        if (q.kind === 'choice') {
          for (const opt of q.options) {
            if (await run(runtime, { ...on, [q.key]: opt.value })) discovered = true;
          }
        }
        // A field left blank by default usually gates something (an icon URL gates its
        // size). Anything non-empty will do; the value is never used.
        if (q.kind === 'text' && q.default === '') {
          if (await run(runtime, { ...on, [q.key]: 'x' })) discovered = true;
        }
      }
    }
    if (!discovered) break;
  }

  return [...byKey.values()];
}
