// Plan → files and commands.
//
// Pure: it takes the answers and returns `{ files, steps }`. Nothing is written here,
// which is what lets a test assert on a generated wrangler.toml without a temp
// directory, and what lets `--dry-run` be the same code path as a real run.
//
// The one rule worth stating out loud: a secret never becomes a file that belongs in
// version control. On Workers that means `[vars]` carries configuration and credentials
// become `wrangler secret put` steps plus a gitignored `.dev.vars` for local runs;
// everywhere else it means a gitignored `.env`. `secret: true` on an entry is the whole
// mechanism — there is no second list to keep in sync.

const RULE = '─'.repeat(58);

/** The exact version, not a range: the two packages are released together, and a drive
 *  whose server and workbench came from different releases is the failure this avoids. */
const pin = (version) => version;

const isSet = (e) => !e.commented && e.value !== '' && e.value != null;

export function renderProject(plan) {
  const files = [];
  const steps = [];
  const secrets = plan.sections.flatMap((s) => s.entries.filter((e) => e.secret && isSet(e)));

  if (plan.runtime === 'workers') renderWorkers(plan, files, steps, secrets);
  else renderServer(plan, files, steps);

  files.push({ path: 'README.md', contents: readme(plan, steps) });
  return { files, steps };
}

// --- shared -----------------------------------------------------------------

/**
 * Render sections as a dotenv file.
 *
 * @param {object[]} sections
 * @param {object} [opts]
 * @param {boolean} [opts.secretsOnly] emit only the credentials — what .dev.vars wants
 * @param {boolean} [opts.omitSecrets] emit everything but the credentials
 */
function renderEnv(sections, { secretsOnly = false, omitSecrets = false } = {}) {
  const out = [];
  for (const section of sections) {
    const entries = section.entries.filter((e) => (secretsOnly ? e.secret : omitSecrets ? !e.secret : true));
    if (!entries.length) continue;
    out.push(`# ${RULE}`);
    out.push(`# ${section.title}${section.skipped ? '  (skipped — fill these in yourself)' : ''}`);
    out.push(`# ${RULE}`);
    for (const e of entries) {
      const comment = e.comment ? `   # ${e.comment}` : '';
      out.push(isSet(e) ? `${e.key}=${e.value}${comment}` : `# ${e.key}=${comment}`);
    }
    out.push('');
  }
  return out.join('\n');
}

const gitignore = (extra = []) => ['node_modules/', '.env', '.dev.vars', ...extra, ''].join('\n');

// --- bun / node --------------------------------------------------------------

function renderServer(plan, files, steps) {
  const { runtime, version, name, server } = plan;
  const exec = runtime === 'bun' ? 'bun' : 'node';
  const adapter = runtime === 'bun' ? 'bun.js' : 'node.js';

  // Bun reads .env on its own; Node needs telling, and --env-file is why this asks for
  // Node 20.6 rather than the 20 the server itself needs.
  const start = runtime === 'bun' ? 'bun server.js' : 'node --env-file=.env server.js';

  files.push({
    path: 'package.json',
    contents: JSON.stringify({
      name,
      private: true,
      type: 'module',
      scripts: { start },
      dependencies: { '@3sln/trove': pin(version) },
      engines: runtime === 'bun' ? { bun: '>=1.1.0' } : { node: '>=20.6' },
    }, null, 2) + '\n',
  });

  files.push({
    path: 'server.js',
    contents: `// Trove, as this project runs it.
//
// The adapter starts listening when it is imported — it reads its configuration from
// the environment (see .env), so there is nothing to pass it. Importing it through the
// package's public export rather than a path into node_modules means this line keeps
// working whatever the installer does with the tree.
//
// To add your own openers or views, this is the file that grows: build a workbench with
// \`createWorkbench({ openers, views })\` from '@3sln/trove/web/workbench.js', bundle it,
// and point TROVE_WEB_DIST at the result.
import '@3sln/trove/server/adapters/${adapter}';
`,
  });

  files.push({ path: '.env', contents: envHeader(plan) + renderEnv(plan.sections) + serverVars(server) });
  files.push({ path: '.gitignore', contents: gitignore(['data/']) });

  steps.push({ cmd: `cd ${name} && npm install`, why: 'pulls @3sln/trove — the web app is already built inside it' });
  steps.push({ cmd: `npm start`, why: `serves the API and the workbench on :${server?.port ?? '8787'}` });
}

const serverVars = (server) => server
  ? [`# ${RULE}`, '# Server', `# ${RULE}`, `PORT=${server.port}`, `HOST=${server.host}`, ''].join('\n')
  : '';

const envHeader = (plan) => `# Generated by create-trove for a ${plan.runtime} deployment.
# Every value here is read at startup. Nothing in this file is committed — see .gitignore.

`;

// --- workers ------------------------------------------------------------------

function renderWorkers(plan, files, steps, secrets) {
  const { name, version, workers: w } = plan;

  files.push({
    path: 'package.json',
    contents: JSON.stringify({
      name,
      private: true,
      type: 'module',
      scripts: { dev: 'wrangler dev', deploy: 'wrangler deploy' },
      dependencies: { '@3sln/trove': pin(version) },
      devDependencies: { wrangler: '^3.90.0' },
    }, null, 2) + '\n',
  });

  files.push({
    path: 'src/worker.js',
    contents: `// The Worker entry.
//
// Both exports matter: the default export is the fetch handler, and TroveTasks is the
// Durable Object class that owns scans and reindexes. Wrangler looks the DO class up by
// name in this module, so re-exporting it here is what makes the binding resolve —
// declaring it in wrangler.toml without this is a deploy-time error.
export { default, TroveTasks } from '@3sln/trove/server/adapters/worker.js';
`,
  });

  files.push({ path: 'wrangler.toml', contents: wranglerToml(plan) });
  files.push({ path: '.gitignore', contents: gitignore(['.wrangler/']) });

  const devVars = renderEnv(plan.sections, { secretsOnly: true });
  if (devVars.trim()) {
    files.push({
      path: '.dev.vars',
      contents: `# Credentials for \`wrangler dev\`. Gitignored, and NOT uploaded by \`wrangler deploy\` —\n`
        + `# the deployed Worker reads these from secrets, which the README lists as commands.\n\n${devVars}`,
    });
  }

  steps.push({ cmd: `cd ${name} && npm install`, why: 'wrangler, and @3sln/trove for the app assets' });
  if (w?.d1) {
    steps.push({
      cmd: `npx wrangler d1 create ${w.d1.name}`,
      why: w.d1.id ? 'already have the id in wrangler.toml — skip if it exists' : 'then paste database_id into wrangler.toml',
    });
  }
  if (w?.pluginDb) {
    steps.push({ cmd: `npx wrangler d1 create ${w.pluginDb.name}`, why: 'server-side plugin storage' });
  }
  if (w?.vectorize) {
    steps.push({
      cmd: `npx wrangler vectorize create ${w.vectorize.index} --dimensions=${w.vectorize.dimensions} --metric=${w.vectorize.metric}`,
      why: 'semantic search — Vectorize is the only vector store that runs here',
    });
  }
  const bucket = plan.sections.flatMap((s) => s.entries).find((e) => e.key === 'TROVE_S3_BUCKET' && isSet(e));
  if (bucket) steps.push({ cmd: `npx wrangler r2 bucket create ${bucket.value}`, why: 'object bytes' });
  for (const s of secrets) {
    steps.push({ cmd: `npx wrangler secret put ${s.key}`, why: 'not in wrangler.toml — secrets never belong in a committed file' });
  }
  steps.push({ cmd: 'npx wrangler deploy', why: '' });
}

function wranglerToml(plan) {
  const { workers: w, sections } = plan;
  const q = (v) => JSON.stringify(String(v));
  const L = [];

  L.push('# Generated by create-trove. Every binding below has a matching command in README.md —');
  L.push('# a wrangler.toml naming a D1 database nobody created deploys fine and fails at request time.');
  L.push('');
  L.push('name = ' + q(plan.name));
  L.push('main = "src/worker.js"');
  L.push(`compatibility_date = ${q(w?.compatibilityDate ?? '2024-09-23')}`);
  L.push('');

  L.push('# The built web app, served straight from the installed package — no build step');
  L.push('# here, because @3sln/trove ships its dist/ inside the tarball.');
  L.push('[assets]');
  L.push('directory = "node_modules/@3sln/trove/packages/web/dist"');
  L.push('binding = "ASSETS"');
  L.push('');

  if (w?.d1) {
    L.push('# Metadata, KV, plugin installs and keyword search. Without this the drive runs');
    L.push('# entirely in memory and loses everything when the isolate recycles.');
    L.push('[[d1_databases]]');
    L.push('binding = "DB"');
    L.push(`database_name = ${q(w.d1.name)}`);
    L.push(`database_id = ${q(w.d1.id || '<run: wrangler d1 create ' + w.d1.name + '>')}`);
    L.push('');
  } else {
    L.push('# [[d1_databases]]          # REQUIRED for anything to persist');
    L.push('# binding = "DB"');
    L.push('# database_name = "trove"');
    L.push('# database_id = "<wrangler d1 create trove>"');
    L.push('');
  }

  if (w?.pluginDb) {
    L.push('# Server-side plugin storage. One database holds every plugin scope: D1 cannot');
    L.push('# create databases on demand, so per-scope databases are not expressible here.');
    L.push('[[d1_databases]]');
    L.push('binding = "PLUGIN_DB"');
    L.push(`database_name = ${q(w.pluginDb.name)}`);
    L.push(`database_id = ${q(w.pluginDb.id || '<run: wrangler d1 create ' + w.pluginDb.name + '>')}`);
    L.push('');
  } else {
    L.push('# [[d1_databases]]          # optional: server-side plugin storage');
    L.push('# binding = "PLUGIN_DB"     # without it that one feature reports a clear error');
    L.push('');
  }

  if (w?.vectorize) {
    L.push('[[vectorize]]');
    L.push('binding = "VECTORIZE"');
    L.push(`index_name = ${q(w.vectorize.index)}`);
    L.push('');
  } else {
    L.push('# [[vectorize]]             # semantic search; sqlite-vec cannot load on Workers');
    L.push('# binding = "VECTORIZE"');
    L.push('# index_name = "trove"');
    L.push('');
  }

  if (w?.ai) {
    L.push('# Turns natural language into semantic text + tag filters; falls back to the');
    L.push('# #tag grammar on error.');
    L.push('[ai]');
    L.push('binding = "AI"');
    L.push('');
  } else {
    L.push('# [ai]                      # optional: LLM query understanding');
    L.push('# binding = "AI"');
    L.push('');
  }

  if (w?.tasks) {
    L.push('# Scans and reindexes live in one Durable Object, so a client polling /api/tasks');
    L.push('# reaches the isolate that actually holds the task and Cancel reaches its');
    L.push('# AbortController. Without it the work still runs, in the request isolate.');
    L.push('[[durable_objects.bindings]]');
    L.push('name = "TASKS"');
    L.push('class_name = "TroveTasks"');
    L.push('');
    L.push('[[migrations]]');
    L.push('tag = "v1"');
    L.push('new_sqlite_classes = ["TroveTasks"]');
    L.push('');
  } else {
    L.push('# [[durable_objects.bindings]]   # optional: owns scans and reindexes');
    L.push('# name = "TASKS"');
    L.push('# class_name = "TroveTasks"');
    L.push('# [[migrations]]');
    L.push('# tag = "v1"');
    L.push('# new_sqlite_classes = ["TroveTasks"]');
    L.push('');
  }

  L.push('[vars]');
  L.push('# Configuration only. Credentials are secrets — see README.md.');
  for (const section of sections) {
    const shown = section.entries.filter((e) => !e.secret);
    if (!shown.length) continue;
    L.push(`# ${section.title}${section.skipped ? '  (skipped)' : ''}`);
    for (const e of shown) {
      const c = e.comment ? `  # ${e.comment}` : '';
      L.push(isSet(e) ? `${e.key} = ${q(e.value)}${c}` : `# ${e.key} = ""${c}`);
    }
  }
  L.push('');
  return L.join('\n');
}

// --- the generated README -----------------------------------------------------

function readme(plan, steps) {
  const L = [];
  const runtimeName = { bun: 'Bun', node: 'Node', workers: 'Cloudflare Workers' }[plan.runtime];

  L.push(`# ${plan.name}`);
  L.push('');
  L.push(`A [Trove](https://github.com/3sln/trove) drive on **${runtimeName}**, scaffolded with \`create-trove\`.`);
  L.push('');
  L.push(`The web app is not built here — \`@3sln/trove@${plan.version}\` ships it already built, so the`);
  L.push('server and the workbench it serves are the same release by construction.');
  L.push('');

  L.push('## Getting it running');
  L.push('');
  L.push('```sh');
  for (const s of steps) L.push(s.why ? `${s.cmd}${' '.repeat(Math.max(1, 44 - s.cmd.length))}# ${s.why}` : s.cmd);
  L.push('```');
  L.push('');

  if (plan.warnings.length) {
    const kind = (w) => (typeof w === 'string' ? w : w.kind);
    const has = (k) => plan.warnings.some((w) => kind(w) === k);
    const found = (k) => plan.warnings.find((w) => kind(w) === k);

    L.push('## Before you expose this');
    L.push('');
    if (has('anonymous')) {
      L.push('- **No identity is configured.** Everyone who can reach the port is the same');
      L.push('  anonymous user. Set `TROVE_AUTH` and `TROVE_AUTH_REQUIRED=true`, and put it behind');
      L.push('  an authenticating proxy over TLS.');
    }
    if (has('incomplete-identity')) {
      const w = found('incomplete-identity');
      L.push(`- **\`TROVE_AUTH=${w.driver}\` is set but incomplete** — ${w.missing.join(', ')} ${w.missing.length > 1 ? 'are' : 'is'} blank.`);
      L.push('  The config reads as configured while the driver has nothing to verify against.');
    }
    if (has('default-open')) {
      L.push('- **The default collection is open.** Every authenticated user gets full');
      L.push('  read/write/delete on it. Set `TROVE_DEFAULT_OPEN=false`.');
    }
    L.push('');
  }

  if (plan.skipped.length) {
    L.push('## Skipped');
    L.push('');
    L.push('Left for you to fill in. The keys are already in place, commented, in');
    L.push(plan.runtime === 'workers' ? '`wrangler.toml`:' : '`.env`:');
    L.push('');
    for (const s of plan.skipped) L.push(`- ${s}`);
    L.push('');
  }

  L.push('## Configuration');
  L.push('');
  L.push(plan.runtime === 'workers'
    ? 'Non-secret settings live in `[vars]` in `wrangler.toml`; credentials are secrets, set with\n`wrangler secret put`, and mirrored into a gitignored `.dev.vars` for `wrangler dev`.'
    : 'Everything is in `.env`, which is gitignored. The full set of variables, with defaults,\nis documented in the Trove README.');
  L.push('');
  return L.join('\n');
}
